# Generated by Django 4.1.2 on 2022-11-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_timr',
            new_name='create_time',
        ),
    ]
