# Generated by Django 4.1.2 on 2022-11-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment_comment_num_comment_down_num_comment_up_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_num',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='down_num',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='up_num',
        ),
    ]
