# Generated by Django 4.1.2 on 2022-11-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_comment_comment_num_remove_comment_down_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='blog',
        ),
    ]
