# Generated by Django 4.1.2 on 2022-11-09 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_category_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.blog'),
        ),
    ]
