# Generated by Django 4.1.2 on 2022-11-09 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类名称')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sort_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sort'),
        ),
    ]
