# Generated by Django 4.1.2 on 2022-11-09 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sort_category_sort_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sort_name',
        ),
        migrations.DeleteModel(
            name='sort',
        ),
    ]
