# Generated by Django 4.1.2 on 2022-11-23 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_category_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章表'},
        ),
    ]
