# Generated by Django 4.1.2 on 2022-11-24 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesRecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('Student_ID', models.CharField(max_length=32, verbose_name='学号')),
                ('campus', models.CharField(max_length=32, verbose_name='校区')),
                ('grade', models.CharField(max_length=32, verbose_name='年级')),
                ('major', models.CharField(max_length=32, verbose_name='专业')),
                ('education', models.CharField(max_length=32, verbose_name='学历')),
                ('Class', models.CharField(max_length=32, verbose_name='班级')),
                ('class_name', models.CharField(max_length=256, verbose_name='班级名')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
