# Generated by Django 4.1.2 on 2022-11-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_classesrecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classesrecode',
            name='user',
        ),
    ]
